version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017 #Mongo work with this port and container
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
#Up MongoDB instance
